# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
# - master

trigger:
  branches:
    include:
      - none

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "9996b419-37a9-49c0-a2d3-5fe80c0680e9"
  containerRegistry: "diplomskacontainerregistry.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)"
  tag: "$(Build.BuildId)"

stages:
  - stage: BuildFrontEnd
    displayName: Build and push front-end
    jobs:
      - job: BuildChallengesFrontend
        displayName: Build challenges-frontend
        pool:
          name: Amar Linux
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
          - script: |
              cd $(Build.SourcesDirectory)/challenges-frontend
              npm install
              npm run build
            displayName: 'npm install and build'
          - task: Docker@2
            displayName: Build and push an front-end image to container registry
            inputs:
              command: buildAndPush
              repository: $(containerRegistry)/challenges-frontend
              dockerfile: $(dockerfilePath)/challenges-frontend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              buildContext: $(Build.SourcesDirectory)/challenges-frontend
              tags: |
                latest

  - stage: BuildBackendServices
    displayName: Build and push backend services
    jobs:
      - job: BuildMultiplication
        displayName: Build multiplication
        pool:
          name: Amar Linux
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: "17"
              jdkArchitectureOption: x64
              jdkSourceOption: LocalDirectory
              jdkFile: "/home/amar/openjdk-17.0.1_linux-x64_bin.tar.gz"
              jdkDestinationDirectory: "/opt/openjdk-17"
              cleanDestinationDirectory: true
          - task: Maven@4
            inputs:
              mavenPomFile: "multiplication/pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.17"
              jdkArchitectureOption: "x64"
              publishJUnitResults: false
              goals: "clean package"
          - task: Docker@2
            displayName: Build and push multiplication service image to container registry
            inputs:
              command: buildAndPush
              repository: $(containerRegistry)/multiplication
              dockerfile: $(dockerfilePath)/multiplication/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest
      - job: BuildGamification
        displayName: Build gamification
        pool:
          name: Amar Linux
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: "17"
              jdkArchitectureOption: x64
              jdkSourceOption: LocalDirectory
              jdkFile: "/home/amar/openjdk-17.0.1_linux-x64_bin.tar.gz"
              jdkDestinationDirectory: "/opt/openjdk-17"
              cleanDestinationDirectory: true
          - task: Maven@4
            inputs:
              mavenPomFile: "gamification/pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.17"
              jdkArchitectureOption: "x64"
              publishJUnitResults: false
              goals: "clean package"        
          - task: Docker@2
            displayName: Build and push gamification image to container registry
            inputs:
              command: buildAndPush
              repository: $(containerRegistry)/gamification
              dockerfile: $(dockerfilePath)/gamification/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest
      - job: Buildgateway
        displayName: Build gateway
        pool:
          name: Amar Linux
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: "17"
              jdkArchitectureOption: x64
              jdkSourceOption: LocalDirectory
              jdkFile: "/home/amar/openjdk-17.0.1_linux-x64_bin.tar.gz"
              jdkDestinationDirectory: "/opt/openjdk-17"
              cleanDestinationDirectory: true
          - task: Maven@4
            inputs:
              mavenPomFile: "gateway/pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.17"
              jdkArchitectureOption: "x64"
              publishJUnitResults: false
              goals: "clean package"        
          - task: Docker@2
            displayName: Build and push gateway image to container registry
            inputs:
              command: buildAndPush
              repository: $(containerRegistry)/gateway
              dockerfile: $(dockerfilePath)/gateway/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest
      - job: Buildlogs
        displayName: Build logs
        pool:
          name: Amar Linux
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: "17"
              jdkArchitectureOption: x64
              jdkSourceOption: LocalDirectory
              jdkFile: "/home/amar/openjdk-17.0.1_linux-x64_bin.tar.gz"
              jdkDestinationDirectory: "/opt/openjdk-17"
              cleanDestinationDirectory: true
          - task: Maven@4
            inputs:
              mavenPomFile: "logs/pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.17"
              jdkArchitectureOption: "x64"
              publishJUnitResults: false
              goals: "clean package"        
          - task: Docker@2
            displayName: Build and push logs image to container registry
            inputs:
              command: buildAndPush
              repository: $(containerRegistry)/logs
              dockerfile: $(dockerfilePath)/logs/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest

  - stage: BuildInfrastructure
    displayName: Build and push infrastructure
    jobs:
      - job: Buildh2
        displayName: Build h2 database
        pool:
          name: Amar Linux
        steps:
          - task: Docker@2
            displayName: Build and push h2 image to container registry
            inputs:
              command: buildAndPush
              repository: $(containerRegistry)/h2-server-dev
              dockerfile: $(dockerfilePath)/docker/h2/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest
      - job: BuildConsul
        displayName: Build consul
        pool:
          name: Amar Linux
        steps:
          - task: Docker@2
            displayName: Build and push consul image to container registry
            inputs:
              command: buildAndPush
              repository: $(containerRegistry)/consul-importer
              dockerfile: $(dockerfilePath)/docker/consul/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest
