version: "3"

services:
  frontend:
    image: diplomskacontainerregistry.azurecr.io/challenges-frontend:latest
    ports:
      - '3000:80'
  multiplication:
    image: diplomskacontainerregistry.azurecr.io/multiplication:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-server:1521/home/h2-data/multiplication;NON_KEYWORDS=USER;
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices
  gamification:
    image: diplomskacontainerregistry.azurecr.io/gamification:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-server:1521/home/h2-data/gamification
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices
  gateway:
    image: diplomskacontainerregistry.azurecr.io/gateway:latest
    ports:
      - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices
  logs:
    image: diplomskacontainerregistry.azurecr.io/logs:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices
  consul-importer:
    image: diplomskacontainerregistry.azurecr.io/consul-importer:latest
    depends_on:
      - consul-dev
    networks:
      - microservices
  consul-dev:
    image: diplomskacontainerregistry.azurecr.io/consul:1.9
    container_name: consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'
    networks:
      - microservices
  rabbitmq-dev:
    image: diplomskacontainerregistry.azurecr.io/rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservices
  h2-server-dev:
    image: diplomskacontainerregistry.azurecr.io/h2-server-dev:latest
    container_name: h2-server
    ports:
      - '81:81'
      - '1521:1521'
    networks:
      - microservices
networks:
  microservices:
    driver: bridge
